### ISSUE TITLE
getfacts_os9.yaml failing on 9.11.0.0

### ISSUE THREAD

**Issue by mzi77** [Dell-Networking/ansible-dellos-examples#1]
getfacts_os9.yaml is giving me error on test S4048 with 9.11.0.0, other playbooks are working OK

PLAY [test0-s4048] *************************************************************

TASK [Gather Dell EMC OS9 Device Facts] ****************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: expected string or buffer
fatal: [test0-s4048]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_tEhMBW/ansible_module_dellos9_facts.py\", line 563, in <module>\n    main()\n  File \"/tmp/ansible_tEhMBW/ansible_module_dellos9_facts.py\", line 552, in main\n    module.exit_json(out=module.from_json(runner.items))\n  File \"/tmp/ansible_tEhMBW/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1782, in from_json\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 338, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib64/python2.7/json/decoder.py\", line 366, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\nTypeError: expected string or buffer\n", "module_stdout": "", "msg": "MODULE FAILURE"}
	to retry, use: --limit @/home/zidek/dev/ansible/ansible-dellos-examples/getfacts_os9.retry

PLAY RECAP *********************************************************************
test0-s4048                : ok=0    changed=0    unreachable=0    failed=1

**Comment by skg-net** [comment]
Hi Martin,

Thanks for letting us know, we are able to recreate the issue. We will fix
it.

Regards,
Senthil Kumar G.

**Comment by wilshire461** [comment]
Seeing this error as well on 9.10, probably has to do with the dellos modules themselves

**Comment by skg-net** [comment]
Hi Wilshire,

Thanks for reporting the issue, Can you provide your running config?

Thanks,
Senthil Kumar G.

**Comment by skg-net** [comment]
@mzi77 Can you please provide your running config?

**Comment by mzi77** [comment]
Hello Senthil, 
currently I don't have spare switch in lab, but it was clean config with ssh access on management port only. I will have lab in few weeks again, so I will post you some results.

**Comment by skg-net** [comment]
Thanks @mzi77. Is your switch management interface used IPv6? We have fixed an issue related to IPv6, wanted to make sure you case is covered as well.

**Comment by mzi77** [comment]
Hello Senthil, no I'm using IPv4 only access.

**Comment by mzi77** [comment]
Hi, tried now on S5000 and FN410S with 9.11.0.0, and it's working OK. Will try on other types too.

**Comment by skg-net** [comment]
Thanks @mzi77.

**Comment by wilshire461** [comment]
@skg-net: I resolved the issue by setting a higher timeout (increased from 5 to 30 seconds) and things started reporting back just fine.

**Comment by skg-net** [comment]
Thanks @wilshire461 @mzi77 As part of this issue testing, we found an issue with IPv6 configuration. 
We have fixed it, PR is in the process of getting merged.  [PR 21652](https://github.com/ansible/ansible/pull/21652)

**Comment by skg-net** [comment]
@wilshire461 Please let us know whether we can close this issue.
