### ISSUE TITLE
Cannot connect to OS9 (PowerConnect 5549P)

### ISSUE THREAD

**Issue by absolutejam** [Dell-Networking/ansible-dellos-examples#4]
Hey guys,

I've managed to connect to my core switches (Force 10 S4810s) with the dellos9 module, but cannot successfully connect to any of my edge switches (PowerConnect 5548Ps) using dellos6 module.

I believe this could be due to the odd way that these switches provide SSH auth, as they use non-standard SSH login prompt (Using `ssh user@switchname` results in the switch still prompting for username & password).

Any ideas on how I can get around this?

Cheers.

**Comment by skg-net** [comment]
@absolutejam Thanks for raising this issue, we will try to recreate this and get back.

**Comment by absolutejam** [comment]
Any movement on this issue? Thanks! :+1:

**Comment by abirami-n** [comment]
@absolutejam ssh auth (ssh user@switchname) , should prompt for password alone.  Can you please provide us with the dellos6 software image version to reproduce?

**Comment by absolutejam** [comment]
Running `show version` on one of my stacks shows the following:
```
       Unit             SW version         Boot version         HW version
------------------- ------------------- ------------------- -------------------
         1               4.1.0.16            1.0.0.14            00.00.02
         2               4.1.0.16            1.0.0.14            00.00.02
         3               4.1.0.16            1.0.0.14            00.00.02
         4               4.1.0.16            1.0.0.14            00.00.02
```

**Comment by absolutejam** [comment]
I thought it could be due to `enable password` being set, but I've unset it and still the same 😢

**Comment by skg-net** [comment]
@absolutejam OS6 version not supported.  Supports version 6.3.1 and above. Please refer
[FAQ](http://ansible-dellos-docs.readthedocs.io/en/latest/faq.html)
